In [2]:
import numpy as np

THE BASICS 


In [4]:
a=np.array([1,2,3], dtype='int32')
print (a)

[1 2 3]


In [6]:
b=np.array([[2.0,3.0,9.0],[8.0,1.0,5.0]])
print (b)

[[2. 3. 9.]
 [8. 1. 5.]]


In [7]:
# dimension
a.ndim

1

In [8]:
# shape
b.shape

(2, 3)

In [9]:
# type
a.dtype

dtype('int32')

In [10]:
# size
a.itemsize

4

In [11]:
# get total size 
a.nbytes

12

In [12]:
# get number of elements
a.size

3

Accessing/changing specific elemts,rows,columns,etc

In [13]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
# get a specific element [r,c]
a[1,2]

10

In [21]:
#specific row 
p=a[0,:]
print(p)

[1 2 3 4 5 6 7]


In [22]:
#specific column 
a[:,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]


array([2, 4, 6])

In [24]:
a[1,3]=20
a[:,2]=[1,2]
print (a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 20 12 13 14]]


3d example
bold text

In [32]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
# get specific element (work outside in)
b [0,1,1] 

4